### ISSUE TITLE
【h5】字体大小不受浏览器缩放改变

### ISSUE THREAD

**Issue by lao-jiawei** [lao-jiawei/lao-jiawei.github.io#50]

**Comment by lao-jiawei** [comment]
# 强制阻止微信调整字体大小
## ios通过设置css阻止：
````css
:root, html {
  -webkit-text-size-adjust: 100% !important;
  -moz-text-size-adjust: 100% !important;
  text-size-adjust: 100% !important;
}
````
## 安卓通过js阻止：
````javascript
// 强制禁止用户修改微信客户端的字体大小
(function() {
  if (typeof WeixinJSBridge === "object" && typeof WeixinJSBridge.invoke === "function") {
    handleFontSize();
  } else {
    if (document.addEventListener) {
      document.addEventListener("WeixinJSBridgeReady", () => handleFontSize(), false);
    } else if (document.attachEvent) {
      document.attachEvent("WeixinJSBridgeReady", () => handleFontSize());
      document.attachEvent("onWeixinJSBridgeReady", () => handleFontSize())
    }
  }
  function handleFontSize() {
    // 设置网页字体为默认大小
    WeixinJSBridge.invoke('setFontSizeCallback', { 'fontSize' : 0 });
    // 重写设置网页字体大小的事件
    WeixinJSBridge.on('menu:setfont', function() {
      WeixinJSBridge.invoke('setFontSizeCallback', { 'fontSize' : 0 });
    });
  }
})();
````
