### ISSUE TITLE
【css】水平垂直居中的方法

### ISSUE THREAD

**Issue by lao-jiawei** [lao-jiawei/lao-jiawei.github.io#59]

**Comment by lao-jiawei** [comment]
> Grid布局

````scss
.test-main {
  width: 100vw;
  height: 50vh;
  background: red;
  
  /* keypoint  */
  display: grid;
  place-items: center;

  .test-child {
    width: 10vw;
    height: 10vw;
    background: green;
  }
}
````

**Comment by lao-jiawei** [comment]
> 相对定位

````scss
  .test-main {
    width: 100vw;
    height: 50vh;
    background: red;

    /* key point */
    position: relative;

    .test-child {
      /* key point */
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);

      width: 10vw;
      height: 10vw;
      background: green;
    }
  }
````
